/*
 *	Autogenerated code from TrainFramework
 *  Created on: {{ date }}
 *      Author: AL
 */

#ifndef _UDP_H_
#define _UDP_H_

typedef struct UdpPacket {
	uint16_t fPort;
	uint16_t tPort;
	uint16_t len;
	uint16_t cksum;
	uint8_t* data;
}__attribute__ ((__packed__))  UdpPacket_st;

typedef struct RailUdp {
	void *car;
	uint64_t command;
	uint8_t* response;
	uint16_t respLen;
	uint16_t respBufLen;
	int socket;
	UdpPacket_st* packet;
	struct sockaddr_in* saddr;
	int slen;
}__attribute__ ((__packed__)) RailUdp_st;

int initUdp(void);
int initUdpClient(uint32_t inetAddress,uint16_t port, uint8_t protocol);
int getUdpClientSocket();

int {{ module['station.name'] }}(void *p);
void {{ module['station.name'] }}Init(void);

#endif /* _UDP_H_ */
