/*
 * pb.h
 * Autogenerated code from TrainFramework
 *
 *  Created on: {{ date }}
 *      Author: home
 */

#ifndef PB_H_
#define PB_H_

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "core-train.h"
#include "core-routes.h"
#include "core-utils.h"

#include "database.h"

int {{ module['station.name'] }}(void *p);
void {{ module['station.name'] }}Init(void);

#endif /* PB_H_ */
