/*
 * ble.h
 * Autogenerated code from TrainFramework
 *
 *  Created on: {{ date }}
 *      Author: ALex
 */

#ifndef _BLE_H_
#define _BLE_H_

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "core-train.h"
#include "core-routes.h"
#include "core-utils.h"

#include "database.h"
#include "serial.h"

typedef struct RailBle{
	void *car;
	uint64_t command;
	uint8_t *response;
	uint16_t respLen;
	uint16_t respBufLen;
	uint8_t **argv;
	uint8_t argc;
	uint8_t *request;
	uint16_t reqLen;
}__attribute__ ((__packed__)) RailBle_st;

typedef struct Beacon{
	uint16_t vid;
	uint16_t major;
	uint16_t minor;
	uint8_t uuid[16];
	uint8_t temp;
	uint8_t hum;
	uint8_t bat;
	uint8_t rsii;
}__attribute__ ((__packed__)) Beacon_st;

{% for define in module.defines %}
#define {{ define.name }}	{{ define.value }}
{% endfor %}


int {{ module.station.name }}(void *p);
void {{ module.station.name }}Init(void);

#endif /* _BLE_H_ */

