/*
 * json.h
 * Autogenerated code from TrainFramework
 *
 *  Created on: {{ date }}
 *      Author: ALex
 */

#ifndef JSON_H_
#define JSON_H_

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "core-train.h"
#include "core-routes.h"
#include "core-utils.h"

{%for module in modules%}
#include "{{module}}.h"
{%endfor%}

typedef struct RailJson{
	void *car;
	uint64_t command;
	char *response;
	uint16_t respLen;
}__attribute__ ((__packed__)) RailJson_st;


int {{ module.station.name }}(void *p);
void {{ module.station.name }}Init(void);

#endif /* JSON_H_ */

