/*
 * {{ module.arrayName }}File.c
 * Autogenerated code from TrainFramework
 *  Created on: {{ date }}
 *      Author: AL
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#include "files.h"


uint8_t {{ module.arrayName }}[] = {
{{module.array}}
};

FileDesc_st {{ module.arrayName }}Descriptor = {
	.fname = "{{ module.filename }}",
	.fsize = {{module.arraySize}},
	.file = {{ module.arrayName }},
	.content = {{ module.content }}
};
